# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.best_time_to_buy_api_url: '%env(default:app.best_time_to_buy_api_url_default:BEST_TIME_TO_BUY_API_URL)%'
    app.best_time_to_buy_api_url_default: 'http://localhost:8002'
    app.best_time_to_buy_api_timeout: '%env(float:default:app.best_time_to_buy_api_timeout_default:BEST_TIME_TO_BUY_API_TIMEOUT)%'
    app.best_time_to_buy_api_timeout_default: 3
    app.b2b_notifications_from: '%env(B2B_NOTIFICATIONS_FROM)%'
    app.b2b_auth_secret: '%env(B2B_AUTH_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\BestTimeToBuyApiClient:
        arguments:
            $bestTimeToBuyApiUrl: 'http://localhost:8002'
            $bestTimeToBuyApiTimeout: '%app.best_time_to_buy_api_timeout%'

    App\Service\B2BNotificationService:
        arguments:
            $fromEmail: '%app.b2b_notifications_from%'

    App\EventSubscriber\B2BAuthSubscriber:
        arguments:
            $authSecret: '%app.b2b_auth_secret%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
