"use client"

import { useCallback, useEffect, useState } from "react"
import { Download, FileText, Search } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import B2BErrorState from "@/components/B2B/b2b-error-state"

type Report = {
  id: number
  type: string
  status: string
  period_start?: string
  period_end?: string
  name?: string
  market_name?: string
  created_at: string
  file_url?: string
}

export default function B2BReportsAdminPage() {
  const [reports, setReports] = useState<Report[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const fetchReports = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch(`/api/b2b/admin/reports?limit=50`)
      if (res.ok) {
        const data = await res.json()
        setReports(data.items || [])
      }
    } catch { setError("Failed to load reports") }
    setLoading(false)
  }, [])

  useEffect(() => { fetchReports() }, [fetchReports])

  const statusColor = (s?: string): string => {
    switch (s?.toUpperCase()) {
      case "GENERATED": return "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400"
      case "PENDING": return "bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400"
      case "ACKNOWLEDGED": return "bg-blue-100 text-blue-700 dark:bg-blue-950/40 dark:text-blue-400"
      default: return "bg-slate-100 text-slate-700"
    }
  }

  return (
    <section className="w-full max-w-none space-y-6">
      <div>
        <h1 className="text-2xl font-bold">B2B Business Reports Archive</h1>
        <p className="text-sm text-muted-foreground">Monitor and manage all business intelligence reports generated by partners.</p>
      </div>

      {error ? (
        <B2BErrorState message={error} onRetry={() => { setError(null); fetchReports() }} />
      ) : (
        <Card>
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-border text-sm">
                <thead className="bg-muted/40 text-left text-xs uppercase tracking-wider text-muted-foreground">
                  <tr>
                    <th className="px-4 py-3 font-medium">ID</th>
                    <th className="px-4 py-3 font-medium">Owner</th>
                    <th className="px-4 py-3 font-medium">Report Type</th>
                    <th className="px-4 py-3 font-medium text-center">Status</th>
                    <th className="px-4 py-3 font-medium">Period</th>
                    <th className="px-4 py-3 font-medium">Generated At</th>
                    <th className="px-4 py-3 font-medium text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/50">
                  {loading ? (
                    Array.from({ length: 5 }).map((_, i) => (
                      <tr key={i}>{Array.from({ length: 7 }).map((_, j) => <td key={j} className="px-4 py-3"><div className="h-4 w-20 animate-pulse rounded bg-muted" /></td>)}</tr>
                    ))
                  ) : reports.length === 0 ? (
                    <tr><td colSpan={7} className="px-4 py-16 text-center">
                      <Search className="mx-auto mb-3 size-10 text-muted-foreground/30" />
                      <p className="text-sm text-muted-foreground">No business reports found.</p>
                    </td></tr>
                  ) : (
                    reports.map((r) => (
                      <tr key={r.id} className="transition-colors hover:bg-muted/20">
                        <td className="px-4 py-3 font-mono text-xs">#{r.id}</td>
                        <td className="px-4 py-3 font-medium">{r.name ?? r.market_name ?? "—"}</td>
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-2">
                            <FileText className="size-3 text-indigo-500" />
                            <span className="text-xs uppercase tracking-wide">{r.type?.replace(/_/g, " ")}</span>
                          </div>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <Badge className={`text-[9px] ${statusColor(r.status)}`}>{r.status}</Badge>
                        </td>
                        <td className="px-4 py-3 text-[10px] text-muted-foreground uppercase">
                          {r.period_start ? new Date(r.period_start).toLocaleDateString() : ""} - {r.period_end ? new Date(r.period_end).toLocaleDateString() : ""}
                        </td>
                        <td className="px-4 py-3 text-xs text-muted-foreground">
                          {new Date(r.created_at).toLocaleString()}
                        </td>
                        <td className="px-4 py-3 text-right">
                          {r.file_url ? (
                            <Button variant="ghost" size="sm" asChild className="h-8 gap-1.5 text-xs">
                               <a href={r.file_url} download><Download className="size-3.5" />Download</a>
                            </Button>
                          ) : "N/A"}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}
    </section>
  )
}
