services:
  db:
    image: postgres:18-alpine
    container_name: productrdar-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-productRadar}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-productRadar}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: productrdar-backend
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-productRadar}?serverVersion=18&charset=utf8
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      php -S 0.0.0.0:8000 -t public

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: productrdar-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://79.137.26.86:8000}
      BACKEND_INTERNAL_URL: http://backend:8000
      ADMIN_SESSION_SECRET: ${ADMIN_SESSION_SECRET}
      B2C_SESSION_SECRET: ${B2C_SESSION_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started

volumes:
  pgdata:
