framework:
    cache:
        prefix_seed: productradar/app
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            products.cache:
                default_lifetime: 300
            listings.cache:
                default_lifetime: 300
            general.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
            doctrine.result_cache_pool:
                default_lifetime: 3600
            doctrine.system_cache_pool:
                default_lifetime: 3600
