<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260419212000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds Module 2 tables: review, data_source, scraping_log.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id INT DEFAULT NULL, product_listing_id INT DEFAULT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT 'PENDING' NOT NULL, moderation_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_794381C619EB6921 ON review (client_id)');
        $this->addSql('CREATE INDEX IDX_794381C64706C231 ON review (product_listing_id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C719EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C71B8D8CD8 FOREIGN KEY (product_listing_id) REFERENCES product_listing (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE data_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, base_url VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, is_active BOOLEAN NOT NULL, last_success_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');

        $this->addSql('CREATE TABLE scraping_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_name VARCHAR(120) NOT NULL, workflow_name VARCHAR(120) NOT NULL, status VARCHAR(20) NOT NULL, duration_ms INT DEFAULT NULL, records_processed INT DEFAULT NULL, error_message TEXT DEFAULT NULL, executed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C719EB6921');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C71B8D8CD8');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE data_source');
        $this->addSql('DROP TABLE scraping_log');
    }
}
