<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402122803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_price_notif BOOLEAN DEFAULT NULL, is_stock_notif BOOLEAN DEFAULT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17FD46C14584665A ON alert (product_id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C14584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE price_history ALTER seller SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C14584665A');
        $this->addSql('DROP TABLE alert');
        $this->addSql('CREATE UNIQUE INDEX unique_category_parent ON category (name, parent_id)');
        $this->addSql('ALTER TABLE price_history ALTER seller DROP NOT NULL');
    }
}
