<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419160405 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin_activity_log DROP CONSTRAINT fk_activity_log_admin');
        $this->addSql('DROP INDEX idx_activity_log_created');
        $this->addSql('DROP INDEX idx_activity_log_type');
        $this->addSql('ALTER TABLE admin_activity_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE admin_activity_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN admin_activity_log.created_at IS \'\'');
        $this->addSql('ALTER TABLE admin_activity_log ADD CONSTRAINT FK_844754AA642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_activity_log_admin RENAME TO IDX_844754AA642B8210');
        $this->addSql('ALTER TABLE category DROP CONSTRAINT unique_category_parent');
        $this->addSql('ALTER TABLE category_link DROP CONSTRAINT category_link_category_id_fkey');
        $this->addSql('ALTER TABLE category_link DROP CONSTRAINT category_link_seller_id_fkey');
        $this->addSql('ALTER TABLE category_link DROP CONSTRAINT category_link_category_id_seller_id_key');
        $this->addSql('ALTER TABLE category_link ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE category_link ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE category_link ADD CONSTRAINT FK_BD37E3B612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE category_link ADD CONSTRAINT FK_BD37E3B68DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin_activity_log DROP CONSTRAINT FK_844754AA642B8210');
        $this->addSql('ALTER TABLE admin_activity_log ALTER id SET DEFAULT nextval(\'admin_activity_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE admin_activity_log ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN admin_activity_log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE admin_activity_log ADD CONSTRAINT fk_activity_log_admin FOREIGN KEY (admin_id) REFERENCES admin (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_activity_log_created ON admin_activity_log (created_at)');
        $this->addSql('CREATE INDEX idx_activity_log_type ON admin_activity_log (entity_type, action)');
        $this->addSql('ALTER INDEX idx_844754aa642b8210 RENAME TO idx_activity_log_admin');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT unique_category_parent UNIQUE (name, parent_id)');
        $this->addSql('ALTER TABLE category_link DROP CONSTRAINT FK_BD37E3B612469DE2');
        $this->addSql('ALTER TABLE category_link DROP CONSTRAINT FK_BD37E3B68DE820D9');
        $this->addSql('ALTER TABLE category_link ALTER id SET DEFAULT nextval(\'category_link_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE category_link ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE category_link ADD CONSTRAINT category_link_category_id_fkey FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category_link ADD CONSTRAINT category_link_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX category_link_category_id_seller_id_key ON category_link (category_id, seller_id)');
    }
}

