<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419160405 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT IF EXISTS unique_category_parent');

        $this->addSql("DO $$ BEGIN IF to_regclass('public.admin_activity_log') IS NOT NULL THEN ALTER TABLE admin_activity_log DROP CONSTRAINT IF EXISTS fk_activity_log_admin; DROP INDEX IF EXISTS idx_activity_log_created; DROP INDEX IF EXISTS idx_activity_log_type; ALTER TABLE admin_activity_log ALTER id DROP DEFAULT; ALTER TABLE admin_activity_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY; COMMENT ON COLUMN admin_activity_log.created_at IS ''; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_844754aa642b8210' AND conrelid = 'admin_activity_log'::regclass) THEN ALTER TABLE admin_activity_log ADD CONSTRAINT FK_844754AA642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) NOT DEFERRABLE; END IF; IF to_regclass('public.idx_activity_log_admin') IS NOT NULL THEN ALTER INDEX idx_activity_log_admin RENAME TO IDX_844754AA642B8210; END IF; END IF; END $$;");

        $this->addSql("DO $$ BEGIN IF to_regclass('public.category_link') IS NOT NULL THEN ALTER TABLE category_link DROP CONSTRAINT IF EXISTS category_link_category_id_fkey; ALTER TABLE category_link DROP CONSTRAINT IF EXISTS category_link_seller_id_fkey; ALTER TABLE category_link DROP CONSTRAINT IF EXISTS category_link_category_id_seller_id_key; ALTER TABLE category_link ALTER id DROP DEFAULT; ALTER TABLE category_link ALTER id ADD GENERATED BY DEFAULT AS IDENTITY; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bd37e3b612469de2' AND conrelid = 'category_link'::regclass) THEN ALTER TABLE category_link ADD CONSTRAINT FK_BD37E3B612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE; END IF; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bd37e3b68de820d9' AND conrelid = 'category_link'::regclass) THEN ALTER TABLE category_link ADD CONSTRAINT FK_BD37E3B68DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) NOT DEFERRABLE; END IF; END IF; END $$;");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql("DO $$ BEGIN IF to_regclass('public.admin_activity_log') IS NOT NULL THEN ALTER TABLE admin_activity_log DROP CONSTRAINT IF EXISTS FK_844754AA642B8210; ALTER TABLE admin_activity_log ALTER id SET DEFAULT nextval('admin_activity_log_id_seq'::regclass); ALTER TABLE admin_activity_log ALTER id DROP IDENTITY; COMMENT ON COLUMN admin_activity_log.created_at IS '(DC2Type:datetime_immutable)'; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_activity_log_admin' AND conrelid = 'admin_activity_log'::regclass) THEN ALTER TABLE admin_activity_log ADD CONSTRAINT fk_activity_log_admin FOREIGN KEY (admin_id) REFERENCES admin (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE; END IF; CREATE INDEX IF NOT EXISTS idx_activity_log_created ON admin_activity_log (created_at); CREATE INDEX IF NOT EXISTS idx_activity_log_type ON admin_activity_log (entity_type, action); IF to_regclass('public.idx_844754aa642b8210') IS NOT NULL THEN ALTER INDEX idx_844754aa642b8210 RENAME TO idx_activity_log_admin; END IF; END IF; END $$;");

        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_category_parent' AND conrelid = 'category'::regclass) THEN ALTER TABLE category ADD CONSTRAINT unique_category_parent UNIQUE (name, parent_id); END IF; END $$;");

        $this->addSql("DO $$ BEGIN IF to_regclass('public.category_link') IS NOT NULL THEN ALTER TABLE category_link DROP CONSTRAINT IF EXISTS FK_BD37E3B612469DE2; ALTER TABLE category_link DROP CONSTRAINT IF EXISTS FK_BD37E3B68DE820D9; ALTER TABLE category_link ALTER id SET DEFAULT nextval('category_link_id_seq'::regclass); ALTER TABLE category_link ALTER id DROP IDENTITY; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'category_link_category_id_fkey' AND conrelid = 'category_link'::regclass) THEN ALTER TABLE category_link ADD CONSTRAINT category_link_category_id_fkey FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE; END IF; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'category_link_seller_id_fkey' AND conrelid = 'category_link'::regclass) THEN ALTER TABLE category_link ADD CONSTRAINT category_link_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE; END IF; CREATE UNIQUE INDEX IF NOT EXISTS category_link_category_id_seller_id_key ON category_link (category_id, seller_id); END IF; END $$;");
    }
}

