<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260419194000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds partner request queue table and extends B2B profiles with full_name.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE partner_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, full_name VARCHAR(255) DEFAULT NULL, account_type VARCHAR(50) NOT NULL, company_name VARCHAR(255) NOT NULL, company_market VARCHAR(255) NOT NULL, company_country VARCHAR(2) NOT NULL, company_website VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_partner_request_created ON partner_request (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_partner_request_email_type ON partner_request (email, account_type)');

        $this->addSql('ALTER TABLE b2b_company ADD full_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE b2b_market ADD full_name VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE b2b_company DROP full_name');
        $this->addSql('ALTER TABLE b2b_market DROP full_name');

        $this->addSql('DROP INDEX idx_partner_request_created');
        $this->addSql('DROP INDEX uniq_partner_request_email_type');
        $this->addSql('DROP TABLE partner_request');
    }
}
