<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260427141136 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE IF NOT EXISTS admin_activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id INT DEFAULT NULL, before_json JSON DEFAULT NULL, after_json JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, admin_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_844754AA642B8210 ON admin_activity_log (admin_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS b2b_company (full_name VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) NOT NULL, company_market VARCHAR(255) DEFAULT NULL, company_country VARCHAR(2) DEFAULT NULL, company_website VARCHAR(255) DEFAULT NULL, b2b_status VARCHAR(50) DEFAULT \'PENDING\' NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_verified BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE IF NOT EXISTS b2b_market (full_name VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) NOT NULL, company_market VARCHAR(255) DEFAULT NULL, company_country VARCHAR(2) DEFAULT NULL, company_website VARCHAR(255) DEFAULT NULL, b2b_status VARCHAR(50) DEFAULT \'PENDING\' NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_verified BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE IF NOT EXISTS category_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url TEXT NOT NULL, category_id INT NOT NULL, seller_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_BD37E3B612469DE2 ON category_link (category_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_BD37E3B68DE820D9 ON category_link (seller_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS data_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, base_url VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, is_active BOOLEAN NOT NULL, last_success_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE IF NOT EXISTS partner_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, full_name VARCHAR(255) DEFAULT NULL, account_type VARCHAR(50) NOT NULL, company_name VARCHAR(255) NOT NULL, company_market VARCHAR(255) NOT NULL, company_country VARCHAR(2) NOT NULL, company_website VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE IF NOT EXISTS review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'PENDING\' NOT NULL, moderation_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT DEFAULT NULL, product_listing_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_794381C619EB6921 ON review (client_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_794381C64706C231 ON review (product_listing_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS scraping_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_name VARCHAR(120) NOT NULL, workflow_name VARCHAR(120) NOT NULL, status VARCHAR(20) NOT NULL, duration_ms INT DEFAULT NULL, records_processed INT DEFAULT NULL, error_message TEXT DEFAULT NULL, executed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');

        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_844754aa642b8210' AND conrelid = 'admin_activity_log'::regclass) THEN ALTER TABLE admin_activity_log ADD CONSTRAINT FK_844754AA642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id) NOT DEFERRABLE; END IF; END $$;");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_23795269bf396750' AND conrelid = 'b2b_company'::regclass) THEN ALTER TABLE b2b_company ADD CONSTRAINT FK_23795269BF396750 FOREIGN KEY (id) REFERENCES \"user\" (id) ON DELETE CASCADE; END IF; END $$;");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ab624e9fbf396750' AND conrelid = 'b2b_market'::regclass) THEN ALTER TABLE b2b_market ADD CONSTRAINT FK_AB624E9FBF396750 FOREIGN KEY (id) REFERENCES \"user\" (id) ON DELETE CASCADE; END IF; END $$;");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bd37e3b612469de2' AND conrelid = 'category_link'::regclass) THEN ALTER TABLE category_link ADD CONSTRAINT FK_BD37E3B612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE; END IF; END $$;");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bd37e3b68de820d9' AND conrelid = 'category_link'::regclass) THEN ALTER TABLE category_link ADD CONSTRAINT FK_BD37E3B68DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) NOT DEFERRABLE; END IF; END $$;");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_794381c619eb6921' AND conrelid = 'review'::regclass) THEN ALTER TABLE review ADD CONSTRAINT FK_794381C619EB6921 FOREIGN KEY (client_id) REFERENCES \"user\" (id) ON DELETE SET NULL NOT DEFERRABLE; END IF; END $$;");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_794381c64706c231' AND conrelid = 'review'::regclass) THEN ALTER TABLE review ADD CONSTRAINT FK_794381C64706C231 FOREIGN KEY (product_listing_id) REFERENCES product_listing (id) ON DELETE SET NULL NOT DEFERRABLE; END IF; END $$;");

        $this->addSql('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS account_status VARCHAR(50) DEFAULT \'ACTIVE\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin_activity_log DROP CONSTRAINT IF EXISTS FK_844754AA642B8210');
        $this->addSql('ALTER TABLE b2b_company DROP CONSTRAINT IF EXISTS FK_23795269BF396750');
        $this->addSql('ALTER TABLE b2b_market DROP CONSTRAINT IF EXISTS FK_AB624E9FBF396750');
        $this->addSql('ALTER TABLE category_link DROP CONSTRAINT IF EXISTS FK_BD37E3B612469DE2');
        $this->addSql('ALTER TABLE category_link DROP CONSTRAINT IF EXISTS FK_BD37E3B68DE820D9');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT IF EXISTS FK_794381C619EB6921');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT IF EXISTS FK_794381C64706C231');
        $this->addSql('DROP TABLE IF EXISTS admin_activity_log');
        $this->addSql('DROP TABLE IF EXISTS b2b_company');
        $this->addSql('DROP TABLE IF EXISTS b2b_market');
        $this->addSql('DROP TABLE IF EXISTS category_link');
        $this->addSql('DROP TABLE IF EXISTS data_source');
        $this->addSql('DROP TABLE IF EXISTS partner_request');
        $this->addSql('DROP TABLE IF EXISTS review');
        $this->addSql('DROP TABLE IF EXISTS scraping_log');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS unique_category_parent ON category (name, parent_id)');
        $this->addSql('ALTER TABLE "user" DROP COLUMN IF EXISTS last_login');
        $this->addSql('ALTER TABLE "user" DROP COLUMN IF EXISTS account_status');
    }
}
