<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416112635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_listing_id INT DEFAULT NULL, client_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA4706C231 ON notification (product_listing_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA19EB6921 ON notification (client_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA4706C231 FOREIGN KEY (product_listing_id) REFERENCES product_listing (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id)');

        $this->addSql('DROP INDEX uniq_68c58ed919eb69214706c231');
        $this->addSql('ALTER TABLE subscription ALTER end_date SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA4706C231');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA19EB6921');
        $this->addSql('DROP TABLE notification');
        $this->addSql('CREATE UNIQUE INDEX unique_category_parent ON category (name, parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_68c58ed919eb69214706c231 ON favorite (client_id, product_listing_id)');
        $this->addSql('ALTER TABLE subscription ALTER end_date DROP NOT NULL');
    }
}
