<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419182236 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("DO $$ BEGIN IF to_regclass('public.moderation_rule') IS NOT NULL THEN DROP INDEX IF EXISTS idx_moderation_rule_is_active; DROP INDEX IF EXISTS idx_moderation_rule_type; ALTER TABLE moderation_rule ALTER id DROP DEFAULT; ALTER TABLE moderation_rule ALTER id ADD GENERATED BY DEFAULT AS IDENTITY; ALTER TABLE moderation_rule ALTER name TYPE VARCHAR(120); ALTER TABLE moderation_rule ALTER rule_type TYPE VARCHAR(50); ALTER TABLE moderation_rule ALTER is_active DROP DEFAULT; ALTER TABLE moderation_rule ALTER config DROP DEFAULT; ALTER TABLE moderation_rule ALTER updated_at DROP NOT NULL; END IF; END $$;");

        $this->addSql("DO $$ BEGIN IF to_regclass('public.notification_log') IS NOT NULL THEN DROP INDEX IF EXISTS idx_notification_read_at; DROP INDEX IF EXISTS idx_notification_sent_at; ALTER TABLE notification_log DROP COLUMN IF EXISTS created_at; ALTER TABLE notification_log ALTER id DROP DEFAULT; ALTER TABLE notification_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY; ALTER TABLE notification_log ALTER notification_type TYPE VARCHAR(50); IF to_regclass('public.idx_notification_recipient') IS NOT NULL THEN ALTER INDEX idx_notification_recipient RENAME TO IDX_ED15DF2E92F8F78; END IF; END IF; END $$;");

        $this->addSql("DO $$ BEGIN IF to_regclass('public.review_response') IS NOT NULL THEN ALTER TABLE review_response DROP CONSTRAINT IF EXISTS fk_review_response_seller; DROP INDEX IF EXISTS idx_review_response_status; ALTER TABLE review_response ALTER id DROP DEFAULT; ALTER TABLE review_response ALTER id ADD GENERATED BY DEFAULT AS IDENTITY; ALTER TABLE review_response ALTER seller_id SET NOT NULL; ALTER TABLE review_response ALTER updated_at DROP NOT NULL; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_1d3982f08de820d9' AND conrelid = 'review_response'::regclass) THEN ALTER TABLE review_response ADD CONSTRAINT FK_1D3982F08DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE NOT DEFERRABLE; END IF; IF to_regclass('public.idx_review_response_review') IS NOT NULL THEN ALTER INDEX idx_review_response_review RENAME TO IDX_1D3982F03E2E969B; END IF; IF to_regclass('public.idx_review_response_seller') IS NOT NULL THEN ALTER INDEX idx_review_response_seller RENAME TO IDX_1D3982F08DE820D9; END IF; END IF; END $$;");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql("DO $$ BEGIN IF to_regclass('public.moderation_rule') IS NOT NULL THEN ALTER TABLE moderation_rule ALTER id SET DEFAULT nextval('moderation_rule_id_seq'::regclass); ALTER TABLE moderation_rule ALTER id DROP IDENTITY; ALTER TABLE moderation_rule ALTER name TYPE VARCHAR(255); ALTER TABLE moderation_rule ALTER rule_type TYPE VARCHAR(100); ALTER TABLE moderation_rule ALTER is_active SET DEFAULT true; ALTER TABLE moderation_rule ALTER config SET DEFAULT '{}'; ALTER TABLE moderation_rule ALTER updated_at SET NOT NULL; CREATE INDEX IF NOT EXISTS idx_moderation_rule_is_active ON moderation_rule (is_active); CREATE INDEX IF NOT EXISTS idx_moderation_rule_type ON moderation_rule (rule_type); END IF; END $$;");

        $this->addSql("DO $$ BEGIN IF to_regclass('public.notification_log') IS NOT NULL THEN ALTER TABLE notification_log ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL; ALTER TABLE notification_log ALTER id SET DEFAULT nextval('notification_log_id_seq'::regclass); ALTER TABLE notification_log ALTER id DROP IDENTITY; ALTER TABLE notification_log ALTER notification_type TYPE VARCHAR(100); CREATE INDEX IF NOT EXISTS idx_notification_read_at ON notification_log (read_at); CREATE INDEX IF NOT EXISTS idx_notification_sent_at ON notification_log (sent_at); IF to_regclass('public.idx_ed15df2e92f8f78') IS NOT NULL THEN ALTER INDEX idx_ed15df2e92f8f78 RENAME TO idx_notification_recipient; END IF; END IF; END $$;");

        $this->addSql("DO $$ BEGIN IF to_regclass('public.review_response') IS NOT NULL THEN ALTER TABLE review_response DROP CONSTRAINT IF EXISTS FK_1D3982F08DE820D9; ALTER TABLE review_response ALTER id SET DEFAULT nextval('review_response_id_seq'::regclass); ALTER TABLE review_response ALTER id DROP IDENTITY; ALTER TABLE review_response ALTER updated_at SET NOT NULL; ALTER TABLE review_response ALTER seller_id DROP NOT NULL; IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_review_response_seller' AND conrelid = 'review_response'::regclass) THEN ALTER TABLE review_response ADD CONSTRAINT fk_review_response_seller FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE; END IF; CREATE INDEX IF NOT EXISTS idx_review_response_status ON review_response (status); IF to_regclass('public.idx_1d3982f03e2e969b') IS NOT NULL THEN ALTER INDEX idx_1d3982f03e2e969b RENAME TO idx_review_response_review; END IF; IF to_regclass('public.idx_1d3982f08de820d9') IS NOT NULL THEN ALTER INDEX idx_1d3982f08de820d9 RENAME TO idx_review_response_seller; END IF; END IF; END $$;");
    }
}
