<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260318172305 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE price_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recorded_price DOUBLE PRECISION NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, out_of_stock BOOLEAN NOT NULL, anomaly BOOLEAN NOT NULL, product_listing_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C9CB8174706C231 ON price_history (product_listing_id)');
        $this->addSql('ALTER TABLE price_history ADD CONSTRAINT FK_4C9CB8174706C231 FOREIGN KEY (product_listing_id) REFERENCES product_listing (id)');
        
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE price_history DROP CONSTRAINT FK_4C9CB8174706C231');
        $this->addSql('DROP TABLE price_history');
        $this->addSql('CREATE UNIQUE INDEX unique_category_parent ON category (name, parent_id)');
    }
}
