<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419182236 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_moderation_rule_is_active');
        $this->addSql('DROP INDEX idx_moderation_rule_type');
        $this->addSql('ALTER TABLE moderation_rule ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE moderation_rule ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE moderation_rule ALTER name TYPE VARCHAR(120)');
        $this->addSql('ALTER TABLE moderation_rule ALTER rule_type TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE moderation_rule ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE moderation_rule ALTER config DROP DEFAULT');
        $this->addSql('ALTER TABLE moderation_rule ALTER updated_at DROP NOT NULL');
        $this->addSql('DROP INDEX idx_notification_read_at');
        $this->addSql('DROP INDEX idx_notification_sent_at');
        $this->addSql('ALTER TABLE notification_log DROP created_at');
        $this->addSql('ALTER TABLE notification_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE notification_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notification_log ALTER notification_type TYPE VARCHAR(50)');
        $this->addSql('ALTER INDEX idx_notification_recipient RENAME TO IDX_ED15DF2E92F8F78');
        $this->addSql('ALTER TABLE review_response DROP CONSTRAINT fk_review_response_seller');
        $this->addSql('DROP INDEX idx_review_response_status');
        $this->addSql('ALTER TABLE review_response ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE review_response ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE review_response ALTER seller_id SET NOT NULL');
        $this->addSql('ALTER TABLE review_response ALTER updated_at DROP NOT NULL');
        $this->addSql('ALTER TABLE review_response ADD CONSTRAINT FK_1D3982F08DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_review_response_review RENAME TO IDX_1D3982F03E2E969B');
        $this->addSql('ALTER INDEX idx_review_response_seller RENAME TO IDX_1D3982F08DE820D9');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE moderation_rule ALTER id SET DEFAULT nextval(\'moderation_rule_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE moderation_rule ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE moderation_rule ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE moderation_rule ALTER rule_type TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE moderation_rule ALTER is_active SET DEFAULT true');
        $this->addSql('ALTER TABLE moderation_rule ALTER config SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE moderation_rule ALTER updated_at SET NOT NULL');
        $this->addSql('CREATE INDEX idx_moderation_rule_is_active ON moderation_rule (is_active)');
        $this->addSql('CREATE INDEX idx_moderation_rule_type ON moderation_rule (rule_type)');
        $this->addSql('ALTER TABLE notification_log ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE notification_log ALTER id SET DEFAULT nextval(\'notification_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE notification_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE notification_log ALTER notification_type TYPE VARCHAR(100)');
        $this->addSql('CREATE INDEX idx_notification_read_at ON notification_log (read_at)');
        $this->addSql('CREATE INDEX idx_notification_sent_at ON notification_log (sent_at)');
        $this->addSql('ALTER INDEX idx_ed15df2e92f8f78 RENAME TO idx_notification_recipient');
        $this->addSql('ALTER TABLE review_response DROP CONSTRAINT FK_1D3982F08DE820D9');
        $this->addSql('ALTER TABLE review_response ALTER id SET DEFAULT nextval(\'review_response_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE review_response ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE review_response ALTER updated_at SET NOT NULL');
        $this->addSql('ALTER TABLE review_response ALTER seller_id DROP NOT NULL');
        $this->addSql('ALTER TABLE review_response ADD CONSTRAINT fk_review_response_seller FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_review_response_status ON review_response (status)');
        $this->addSql('ALTER INDEX idx_1d3982f03e2e969b RENAME TO idx_review_response_review');
        $this->addSql('ALTER INDEX idx_1d3982f08de820d9 RENAME TO idx_review_response_seller');
    }
}
